name: 'SPSauce Build'
description: 'Run a SPSauce build script to fetch dependencies, compile and create release artifacts for your SourceMod plugins.'
branding:
  color: 'orange'
  icon: 'package'
inputs:
  script:
    description: 'Path of the spsauce file to run'
    required: true
    default: 'git.sauce'
  args:
    description: 'Additional Arguments for sps'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ github.token }}
  args:
    - ${{ inputs.script }}
    - ${{ inputs.args }}